<?php


return [
    'theme_7' => [
        '__featured__products' => 'Sản phẩm nổi bật',
        '__featured__keywords' => 'Từ khoá nổi bật',
        '__streamer' => 'Streamer/ Idol khuyên dùng',
        '__price__matching' => 'Giá phù hợp',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
        '__banner__category' => 'Banner Danh mục',
        // '__entertainment' => 'Giải trí',
         '__study' => 'Học tập',
        '__no__acc' => 'Chưa có tài khoản',
    ],
    'theme_thailan' => [
        '__header__home__v1' => 'Header Shop Brand',
        '__header__home__v2' => 'Header Shop Brand V2',
        '__slider__banner__home' => 'Slider Banner',
        '__dich__vu__noi__bat' => 'Dịch vụ nổi bật',
        '__gia__soc' => 'Giá sốc',
        '__recommend' => 'Gợi ý',
        '__content__home__statistic' => 'Thống kê',
        '__setting__discord__facebook' => 'Cấu hình discord và facebook',
        '__top__trong__ngay' => 'Top trong ngày',
        '__danh__cho__ban' => 'Dành cho bạn',
        '__content__home__minigame' => 'Vòng quay',
        '__napthe' => 'Nạp tiền',
        '__mua__the' => 'Mua thẻ',
        '__content__home__dichvu' => 'Dịch vụ game (Dạng slider)',
        '__content__home__dichvu__v2' => 'Dịch vụ (Dạng danh sách)',
        '__content__home__game' => 'Nick ngon giá rẻ',
        '__content__home__game__random' => 'Mua nick random',
        '__content__home__game_thuong' => 'Mua nick Thường',
        '__content__home__detail__random' => 'Chi tiết random 4 danh mục nick',
        '__services__other' => 'Dịch vụ khác',
        '__tin__tuc' => 'Tin tức',
        '__abount__us' => 'Về chúng tôi',
        '__intro__text' => 'Intro text',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_robux_2' => [
        '__header__home__v1' => 'Header Shop Brand',
        '__header__home__v2' => 'Header Shop Brand V2',
        '__slider__banner__home' => 'Slider Banner',
        '__slider__banner__home__menu' => 'Slider Banner (Dạng có danh mục)',
        '__dich__vu__noi__bat' => 'Dịch vụ nổi bật (Dạng hình ảnh)',
        '__dich__vu__noi__bat__text' => 'Dịch vụ nổi bật (Dạng text)',
        '__gia__soc' => 'Giá sốc',
        '__recommend' => 'Gợi ý',
        '__content__home__statistic' => 'Thống kê',
        '__setting__discord__facebook' => 'Cấu hình discord và facebook',
        '__top__trong__ngay' => 'Top trong ngày',
        '__danh__cho__ban' => 'Dành cho bạn',
        '__content__home__minigame' => 'Vòng quay',
        '__napthe' => 'Nạp tiền',
        '__mua__the' => 'Mua thẻ',
        '__content__home__dichvu' => 'Dịch vụ game (Dạng slider)',
        '__content__home__dichvu__v2' => 'Dịch vụ (Dạng danh sách)',
        '__content__home__game' => 'Nick ngon giá rẻ',
        '__content__home__game__random' => 'Mua nick random',
        '__content__home__game_thuong' => 'Mua nick Thường',
        '__content__home__detail__random' => 'Chi tiết random 4 danh mục nick',
        '__services__other' => 'Dịch vụ khác',
        '__tin__tuc' => 'Tin tức',
        '__abount__us' => 'Về chúng tôi',
        '__intro__text' => 'Intro text',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_robux' => [
        '__header__home__v1' => 'Header Shop Brand',
        '__header__home__v2' => 'Header Shop Brand V2',
        '__slider__banner__home' => 'Slider Banner',
        '__dich__vu__noi__bat' => 'Dịch vụ nổi bật',
        '__gia__soc' => 'Giá sốc',
        '__recommend' => 'Gợi ý',
        '__content__home__statistic' => 'Thống kê',
        '__setting__discord__facebook' => 'Cấu hình discord và facebook',
        '__top__trong__ngay' => 'Top trong ngày',
        '__danh__cho__ban' => 'Dành cho bạn',
        '__content__home__minigame' => 'Vòng quay',
        '__napthe' => 'Nạp tiền',
        '__mua__the' => 'Mua thẻ',
        '__content__home__dichvu' => 'Dịch vụ game (Dạng slider)',
        '__content__home__dichvu__v2' => 'Dịch vụ (Dạng danh sách)',
        '__content__home__game' => 'Nick ngon giá rẻ',
        '__content__home__game__random' => 'Mua nick random',
        '__content__home__game_thuong' => 'Mua nick Thường',
        '__content__home__detail__random' => 'Chi tiết random 4 danh mục nick',
        '__services__other' => 'Dịch vụ khác',
        '__tin__tuc' => 'Tin tức',
        '__abount__us' => 'Về chúng tôi',
        '__intro__text' => 'Intro text',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_5' => [
        '__header__home__v1' => 'Header Shop Brand',
        '__header__home__v2' => 'Header Shop Brand V2',
        '__slider__banner__home' => 'Slider Banner (Có quảng cáo)',
        '__slider__banner' => 'Slider Banner (Không có quảng cáo)',
        '__dich__vu__noi__bat' => 'Dịch vụ nổi bật',
        '__gia__soc' => 'Giá sốc',
        '__top__trong__ngay' => 'Top trong ngày',
        '__danh__cho__ban' => 'Dành cho bạn',
        '__content__home__minigame' => 'Vòng quay',
        '__napthe' => 'Nạp tiền',
        '__mua__the' => 'Mua thẻ',
        '__content__home__dichvu' => 'Dịch vụ game (Dạng slider)',
        '__content__home__dichvu__v2' => 'Dịch vụ (Dạng danh sách)',
        '__content__home__game' => 'Nick ngon giá rẻ',
        '__content__home__game__random' => 'Mua nick random',
        '__content__home__game_thuong' => 'Mua nick Thường',
        '__content__home__detail__random' => 'Chi tiết random 4 danh mục nick',
        '__services__other' => 'Dịch vụ khác',
        '__tin__tuc' => 'Tin tức',
        '__abount__us' => 'Về chúng tôi',
        '__intro__text' => 'Intro text',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_3' => [
        '__slider__banner__home' => 'Slider trang chủ',
        '__slider__banner' => 'Slider trang chủ (V2)',
        '__list_serve_remark' => 'Dịch vụ nổi bật',
        '__list_serve_remark_mobile' => 'Dịch vụ nổi bật mobile',
        '__hotsale' => 'Giá sốc',
        '__play__recently__home' => 'Dành cho bạn',
        '__top_nap_the_mobile' => 'Top nạp thẻ mobile',
        '__service_game' => 'Dịch vụ game',
        '__content__home__minigame' => 'Vòng quay',
        '__nap_the' => 'Nạp tiền',
        '__card_purchase' => 'Mua thẻ',
        '__buy__acc__home' => 'Nick ngon giá rẻ',
        '__content__home__game__random' => 'Mua nick random',
        '__content__home__game_thuong' => 'Mua nick Thường',
        '__random__account' => 'Chi tiết random 4 danh mục nick',
        '__list_serve_remark_image' => 'Dịch vụ nổi bật v2',
        '__tin__tuc' => 'Tin tức',
        '__abount__us' => 'Về chúng tôi',
        '__intro__text' => 'Intro text',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_1' => [
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
        '__card__purchase' => 'Mua thẻ',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
    'theme_4' => [
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
    ],
    'theme_card_1' => [
        '__card_purchase' => 'mua thẻ online',
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
        '__dichvu__lienquan' => 'Dịch vụ liên quan',
        '__intro__text' => 'Intro text',
    ],
    'theme_card_2' => [
        '__slider__banner' => 'Slider banner',
        '__card_purchase' => 'mua thẻ online',
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
        '__list_serve_remark_image' => 'Dịch vụ liên quan',
        '__intro__text' => 'Intro text',
        '__baiviet__trangchu' => 'Bài viết',
    ],
    'theme_2' => [
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
        '__list_serve_remark_image' => 'Dịch vụ liên quan',
    ],
    'theme_dup' => [
        '__content__home__game' => 'Danh mục game',
        '__content__home__dichvu' => 'Dịch vụ game',
        '__content__home__minigame' => 'Danh mục minigame',
        '__nick__option__one' => 'Nick lựa chọn 1',
        '__nick__option__two' => 'Nick lựa chọn 2',
        '__nick__option__three' => 'Nick lựa chọn 3',
        '__service__option__one' => 'Dịch vụ lựa chọn 1',
        '__service__option__two' => 'Dịch vụ lựa chọn 2',
        '__service__option__three' => 'Dịch vụ lựa chọn 3',
    ],
];










