<?php


return [
    'PC-1_MEmu-1' => [
        "Spider TV",
        "Chef TV Man",
        "Upgraded Titan Cinemaman",
        "Corrupted Cameraman",
        "Engineer Cameraman",
        "Sinister Cameraman",
        "Glitch Cameraman",
        "Upgraded Titan Speakerman",
        "Upgraded Titan Cameraman",
        "Scientist TV Man",
        "Hot Dog Speakerman",
        "Titan Boombox Man",
        "Hamburger TV Man",
        "Axe Upgraded Titan Speakerman",
        "Sword Large Cameraman",
    ],
    'PC-1_MEmu-2' => [
        "Titan Cinemaman",
        "Large Turkey Speakerman",
        "Shield Cameraman",
        "Pumpkin Farmer",
        "Monster Speakerman",
        "Titan Cameraman",
        "Camera Repair Drone",
        "Jetpack Cameraman",
        "Turkey Cameraman",
        "Scientist Cameraman",
        "DJ Toilet",
        "Lifeguard Speakerman",
        "Saber Mutant Toilet",
        "Titan Mogman",
        "Evil Tv Man",
        "Titan Heart Man"
    ],
    'PC-1_MEmu-3' => [
        "Camera Spider",
        "Speaker Spider",
        "Large Scientist Cameraman",
        "Ninja Cameraman",
        "Laser Cameraman Car",
        "TV Woman",
        "Mech Cameraman",
        "Dark Speakerman",
        "Secret Agent",
        "Titan TV Man",
        "Torch TV Man",
        "Volcanic Titan",
        "Cameraman Car",
        "Sniper Cameraman",
        "Vampire Cameraman",
        "Witch Camerawoman"
    ],
    'PC-1_MEmu-4' => [
        "Titan Speakerman",
        "Dancing Speakerwoman",
        "Jetpack Speakerman",
        "Sinister Titan TV Man",
        "Titan Present Man",
        "Frost DJ Speakerman",
        "Santa TV Man",
        "Elf Camerawoman",
        "Reindeer Speakerman",
        "Green Laser Cameraman",
        "Buff Mutant Toilet",
        "Mutant Toilet",
        "Upgraded Camerawoman",
        "Smooth Toilet",
        "Chair",
        "Zombie Horde Cameraman"
    ],
    'PC-1_MEmu-5' => [
        "Firework Cameraman",
        "Mace Cameraman",
        "Large Firework Cameraman",
        "Laser Gun Cameraman",
        "Bat Speakerman",
        "Hunter Cameraman",
        "Speaker Repair Drone",
        "Dual Bat Speakerman",
        "Large Laser Cameraman",
        "Flamethrower Cameraman",
        "Strider Toilet",
        "Swat Mutant Toilet",
        "Cage Scientist Clockman",
        "Creator Pencilman",
    ],
    'PC-1_MEmu-6' => [
        "Minigun Camerawoman",
        "Katana Speakerwoman",
        "Shotgun Cameraman",
        "Announcer Cameraman",
        "DJ Speakerman",
        "Dj TV Man",
        "Ghost Cameraman",
        "Spear Speakerman",
        "Jetpack Mace Cameraman",
        "Titan Clock Man",
        "Boss Toilet",
        "Solar Flare TV Man",
        "Commander Cameraman",
        "Titan Pencil Woman",
        "King Drillman",
        "Sergeant Drillman"
    ],
    'PC-1_MEmu-7' => [
        "Toxic Upgraded Titan Cameraman",
        "Hyper Upgraded Titan Speakerman",
        "Titan Drill Man",
        "Large Heart Speakerman",
        "Speakerwoman's Rose Farm",
        "Cupid Camerawoman",
        "Healer TV Woman",
        "Speaker Large TV Man",
        "Red Laser Cameraman",
        "Future Large Clockman",
        "Clockwoman",
        "Titan Sigma Man",
        "Coconut Cameraman",
        "Summoner Pencilman",
        "Eternal Clock Titan",
        "Toilet Man",
    ],
    'PC-1_MEmu-8' => [
        "Lucky Speakerman",
        "Leprechaun Cameraman",
        "Titan Clover Man",
        "Titan Bunny Cameraman",
        "Mech Bunny Titan",
        "Egg Launcher Cameraman",
        "Large Bunnyman",
        "Dual Blade Bunnyman",
        "Easter Speakerman",
        "Upgraded Camera Spider",
        "Gravity Gun Cameraman",
        "Static Speakerman",
        "Pencil Helicopter",
        "Hourglass Speakerman",
        "Corporal Drillman",
        "Cheese Drillman"
    ],
    'PC-1_MEmu-9' => [
        "Upgraded Mech Cameraman",
        "Mewing TV Man",
        "Medic Cameraman",
        "Astro Upgraded Titan Cameraman",
        "Mace Camerawoman",
        "Scientist Mech",
        "Knife Upgraded Titan Speakerman",
        "Upgraded Large Laser Cameraman",
        "Astro Gun Cameraman",
        "Titan Sand Man",
        "Surfer TV Man",
        "Alarm Clockman",
        "Pencil Mech",
        "Hammer Pencilman",
        "Very Important Titan",
        "Telanthric"
    ],
    'PC-1_MEmu-10' => [
        "Large Clockman",
        "Pendulum Clockman",
        "Cuckoo Clockman",
        "Chief Clockman",
        "Guardian Clockman",
        "Clock Spider",
        "Scientist Clockman",
        "Shadow TV Man",
        "Golden Future Large Clockman",
        "Beret Cameraman",
        'Demented Titan Cameraman',
        "Titan Meatball Man",
        "Ice Cream Speakerman",
        "iamEvan",
        "Sigma Drillman"
    ],
    'PC-1_MEmu-11' => [
        "Saw Upgraded Titan Cameraman",
        "Turkey Speakerman",
        "Streamer Cameraman",
        "Upgraded Titan Drill Man",
        "Upgraded Titan Clockman",
        "Fanman",
        "Large Fanman",
        "Titan Fanman",
        "Sparkler Cameraman",
        "Titan Firework Man",
        "Arachnid Militant Toilet",
        "Military Mutant Toilet Girl",
        "Titan Beach Ball Man",
        "Aquatitan Speakerman",
        "Sand Wizard Cameraman",
        "Pool",
        "Starfall TV Man",
        "VIP Cameraman",
        "Speaker Drill Pencil Clock TV Cameraman"
    ],
    'PC-1_MEmu-12' => [
        "Layered Drillman",
        "Upgraded Refined Drillman",
        "Large Drillman",
        "Drill Helicopter",
        "Dark Drillman",
        "Assassin Drillman",
        "Armored Drillman",
        "Scientist Drillman",
        "Chief Drillman",
        "Astro Large TV Man",
        "Drill Woman",
        "Titan Printer Man",
        "Large Printer Man",
        "Dark Printer Man",
        "Printer Man",
        "Refined Drilman",
        "Skeleton Cameraman",
        "Grim Reaperman",
        "Titan Doomspeaker",
        "Titan Alien Man"
    ],
];










