<?php
/**
 * Created by PhpStorm.
 * User: MyPC
 * Date: 10/10/2018
 * Time: 10:37 CH
 */
const WITHDRAW_RUBY_DAILY_LIMIT = 'WITHDRAW_RUBY_DAILY_LIMIT';
const USER_NON_LIMIT_WITHDRAW_RUBY_DAILY = 'USER_NON_LIMIT_WITHDRAW_RUBY_DAILY';


const SETTING_SYSTEM_BACKGROUND_NST = 'SETTING_SYSTEM_BACKGROUND_NST';

const SETTING_SYSTEM_BONUS_IMAGE_ICON = 'SETTING_SYSTEM_BONUS_IMAGE_ICON';
const SETTING_SYSTEM_BONUS_WHEEL_TYPE_VP = 'SETTING_SYSTEM_BONUS_WHEEL_TYPE_VP';
const SETTING_SYSTEM_BONUS_MONEY = 'SETTING_SYSTEM_BONUS_MONEY';
const SETTING_SYSTEM_BONUS_MONEY_TO = 'SETTING_SYSTEM_BONUS_MONEY_TO';
const SETTING_SYSTEM_BONUS_MONEY_TYPE = 'SETTING_SYSTEM_BONUS_MONEY_TYPE';
const SETTING_SYSTEM_BONUS_MONEY_TYPE_VP = 'SETTING_SYSTEM_BONUS_MONEY_TYPE_VP';
const SETTING_SYSTEM_BONUS_CONTENT = 'SETTING_SYSTEM_BONUS_CONTENT';
const SETTING_SYSTEM_BONUS_CONTENT_AFTER = 'SETTING_SYSTEM_BONUS_CONTENT_AFTER';
//constant setting system
const SETTING_SYSTEM_BORDER_ITEM_CAT= 'SETTING_SYSTEM_BORDER_ITEM_CAT';
const SETTING_SYSTEM_LIST_USER_SPECIAL_REVICE_BONUS = 'SETTING_SYSTEM_LIST_USER_SPECIAL_REVICE_BONUS';

const SETTING_GOOGLE_TASK_MANAGER_HEAD='SETTING_GOOGLE_TASK_MANAGER_HEAD';
const SETTING_GOOGLE_TASK_MANAGER_BODY='SETTING_GOOGLE_TASK_MANAGER_BODY';

const SETTING_SYSTEM_TITLE = 'SETTING_SYSTEM_TITLE';
const SETTING_NOTICE_TOPUP_SEND_CAROT_VALUE = 'SETTING_NOTICE_TOPUP_SEND_CAROT_VALUE';
const SETTING_NOTICE_TOPUP_CAROT_VALUE = 'SETTING_NOTICE_TOPUP_CAROT_VALUE';

const SETTING_SYSTEM_DESCRIPTION = 'SETTING_SYSTEM_DESCRIPTION';
const SETTING_SYSTEM_WEBSITE = 'SETTING_SYSTEM_WEBSITE';
const SETTING_SYSTEM_WEBSITE_VNU = 'SETTING_SYSTEM_WEBSITE_VNU';
const SETTING_SYSTEM_KEYWORD = 'SETTING_SYSTEM_KEYWORD';
const SETTING_SYSTEM_ADDRESS = 'SETTING_SYSTEM_ADDRESS';
const SETTING_SYSTEM_PHONE = 'SETTING_SYSTEM_PHONE';
const SETTING_SYSTEM_FAX = 'SETTING_SYSTEM_FAX';
const SETTING_SYSTEM_HOTLINE = 'SETTING_SYSTEM_HOTLINE';
const SETTING_SYSTEM_EMAIL = 'SETTING_SYSTEM_EMAIL';
const SETTING_SYSTEM_FANPAGE_FACEBOOK = 'SETTING_SYSTEM_FANPAGE_FACEBOOK';
const SETTING_SYSTEM_FANPAGE_GOOGLE = 'SETTING_SYSTEM_FANPAGE_GOOGLE';
const SETTING_SYSTEM_FANPAGE_TWITTER = 'SETTING_SYSTEM_FANPAGE_TWITTER';
const SETTING_SYSTEM_LINKYOUTUBE = 'SETTING_SYSTEM_LINKYOUTUBE';
const SETTING_SYSTEM_GOOGLE_ANALYTICS = 'SETTING_SYSTEM_GOOGLE_ANALYTICS';
const SETTING_SYSTEM_LOGO = 'SETTING_SYSTEM_LOGO';
const SETTING_SYSTEM_BACKGROUND = 'SETTING_SYSTEM_BACKGROUND';
const SETTING_SYSTEM_LOGO1 = 'SETTING_SYSTEM_LOGO1';
const SETTING_SYSTEM_LOGO_MOBILE = 'SETTING_SYSTEM_LOGO_MOBILE';
const SETTING_SYSTEM_FAVICON = 'SETTING_SYSTEM_FAVICON';
const SETTING_SYSTEM_LOGO_FOOTER = 'SETTING_SYSTEM_LOGO_FOOTER';
const SETTING_SYSTEM_FOOTER_CONTENT = 'SETTING_SYSTEM_FOOTER_CONTENT';
const SETTING_SYSTEM_NOTI_POPUP = 'SETTING_SYSTEM_NOTI_POPUP';
const SETTING_SYSTEM_NOTI_POPUP_ADMIN = 'SETTING_SYSTEM_NOTI_POPUP_ADMIN';
const SETTING_SYSTEM_MAIL_USER = 'SETTING_SYSTEM_MAIL_USER';
const SETTING_SYSTEM_MAIL_PASSWORD = 'SETTING_SYSTEM_MAIL_PASSWORD';
const SETTING_SYSTEM_SOLOGAN = 'SETTING_SYSTEM_SOLOGAN';
const SETTING_GOOGLE_ANATYLICS = 'SETTING_GOOGLE_ANATYLICS';

// cau hinh
const SETTING_SYSTEM_TIME_WORK = 'SETTING_SYSTEM_TIME_WORK';
const SETTING_SYSTEM_TUT_ATM = 'SETTING_SYSTEM_TUT_ATM';
const SETTING_SYSTEM_TUT_VI = 'SETTING_SYSTEM_TUT_VI';
const SETTING_SYSTEM_GIAI_THUONG = 'SETTING_SYSTEM_GIAI_THUONG';
const SETTING_SYSTEM_FOOTER_CONTENT1 = 'SETTING_SYSTEM_FOOTER_CONTENT1';
const SETTING_SYSTEM_FOOTER_CONTENT2 = 'SETTING_SYSTEM_FOOTER_CONTENT2';
const SETTING_SYSTEM_ATM1 = 'SETTING_SYSTEM_ATM1';
const SETTING_SYSTEM_ATM2 = 'SETTING_SYSTEM_ATM2';

// cau hinh thoi gian hien thi lai poup
const SETTING_SYSTEM_NOTI_POPUP_TIME = 'SETTING_SYSTEM_NOTI_POPUP_TIME';

// cau hinh canh bao luc mua xong tai khoan
const SETTING_SYSTEM_WARN_ACC1 = 'SETTING_SYSTEM_WARN_ACC1';
const SETTING_SYSTEM_WARN_ACC2 = 'SETTING_SYSTEM_WARN_ACC2';

// cau hinh vi tri vang, ngoc, xu, bac
const SETTING_SYSTEM_GEM_PLACE = 'SETTING_SYSTEM_GEM_PLACE';
const SETTING_SYSTEM_GOLD_PLACE = 'SETTING_SYSTEM_GOLD_PLACE';
const SETTING_SYSTEM_COIN_PLACE = 'SETTING_SYSTEM_COIN_PLACE';
const SETTING_SYSTEM_XU_PLACE = 'SETTING_SYSTEM_XU_PLACE';

// cau hinh menu user
const SETTING_SYSTEM_MENU = 'SETTING_SYSTEM_MENU';

// cau hình an hien danh muc trang chu
const SETTING_SYSTEM_CATE_HOME = 'SETTING_SYSTEM_CATE_HOME';

// cau hinh ruby

const WITHDRAW_RUBY_LIMIT = 30;
const SETTING_SYSTEM_RUBY_GAME_TYPE1 = 'SETTING_SYSTEM_RUBY_GAME_TYPE1';
const SETTING_SYSTEM_RUBY_GAME_TYPE2 = 'SETTING_SYSTEM_RUBY_GAME_TYPE2';
const SETTING_SYSTEM_RUBY_GAME_TYPE3 = 'SETTING_SYSTEM_RUBY_GAME_TYPE3';
const SETTING_SYSTEM_RUBY_GAME_TYPE4 = 'SETTING_SYSTEM_RUBY_GAME_TYPE4';
const SETTING_SYSTEM_RUBY_GAME_TYPE5 = 'SETTING_SYSTEM_RUBY_GAME_TYPE5';
const SETTING_SYSTEM_RUBY_GAME_TYPE6 = 'SETTING_SYSTEM_RUBY_GAME_TYPE6';
const SETTING_SYSTEM_RUBY_GAME_TYPE7 = 'SETTING_SYSTEM_RUBY_GAME_TYPE7';
const SETTING_SYSTEM_RUBY_GAME_TYPE8 = 'SETTING_SYSTEM_RUBY_GAME_TYPE8';
const SETTING_SYSTEM_RUBY_GAME_TYPE9 = 'SETTING_SYSTEM_RUBY_GAME_TYPE9';

const SETTING_SYSTEM_RUBY_TITLE1 = 'SETTING_SYSTEM_RUBY_TITLE1';
const SETTING_SYSTEM_RUBY_NOW1 = 'SETTING_SYSTEM_RUBY_NOW1';
const SETTING_SYSTEM_DROPDOWN_NAME1 = 'SETTING_SYSTEM_DROPDOWN_NAME1';
const SETTING_SYSTEM_ID_IN_GAME1 = 'SETTING_SYSTEM_ID_IN_GAME1';
const SETTING_SYSTEM_RUBY_CONTENT1 = 'SETTING_SYSTEM_RUBY_CONTENT1';
const SETTING_SYSTEM_RUBY_PHONE1 = 'SETTING_SYSTEM_RUBY_PHONE1';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_1 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_1';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_1 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_1';


const SETTING_SYSTEM_RUBY_TITLE2 = 'SETTING_SYSTEM_RUBY_TITLE2';
const SETTING_SYSTEM_RUBY_NOW2 = 'SETTING_SYSTEM_RUBY_NOW2';
const SETTING_SYSTEM_DROPDOWN_NAME2 = 'SETTING_SYSTEM_DROPDOWN_NAME2';
const SETTING_SYSTEM_ID_IN_GAME2 = 'SETTING_SYSTEM_ID_IN_GAME2';
const SETTING_SYSTEM_RUBY_CONTENT2 = 'SETTING_SYSTEM_RUBY_CONTENT2';
const SETTING_SYSTEM_RUBY_PHONE2 = 'SETTING_SYSTEM_RUBY_PHONE2';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_2 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_2';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_2 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_2';

const SETTING_SYSTEM_RUBY_TITLE3 = 'SETTING_SYSTEM_RUBY_TITLE3';
const SETTING_SYSTEM_RUBY_NOW3 = 'SETTING_SYSTEM_RUBY_NOW3';
const SETTING_SYSTEM_DROPDOWN_NAME3 = 'SETTING_SYSTEM_DROPDOWN_NAME3';
const SETTING_SYSTEM_ID_IN_GAME3 = 'SETTING_SYSTEM_ID_IN_GAME3';
const SETTING_SYSTEM_RUBY_CONTENT3 = 'SETTING_SYSTEM_RUBY_CONTENT3';
const SETTING_SYSTEM_RUBY_PHONE3 = 'SETTING_SYSTEM_RUBY_PHONE3';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_3 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_3';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_3 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_3';

const SETTING_SYSTEM_RUBY_TITLE4 = 'SETTING_SYSTEM_RUBY_TITLE4';
const SETTING_SYSTEM_RUBY_NOW4 = 'SETTING_SYSTEM_RUBY_NOW4';
const SETTING_SYSTEM_DROPDOWN_NAME4 = 'SETTING_SYSTEM_DROPDOWN_NAME4';
const SETTING_SYSTEM_ID_IN_GAME4 = 'SETTING_SYSTEM_ID_IN_GAME4';
const SETTING_SYSTEM_RUBY_CONTENT4 = 'SETTING_SYSTEM_RUBY_CONTENT4';
const SETTING_SYSTEM_RUBY_PHONE4 = 'SETTING_SYSTEM_RUBY_PHONE4';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_4 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_4';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_4 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_4';

const SETTING_SYSTEM_RUBY_TITLE5 = 'SETTING_SYSTEM_RUBY_TITLE5';
const SETTING_SYSTEM_RUBY_NOW5 = 'SETTING_SYSTEM_RUBY_NOW5';
const SETTING_SYSTEM_DROPDOWN_NAME5 = 'SETTING_SYSTEM_DROPDOWN_NAME5';
const SETTING_SYSTEM_ID_IN_GAME5 = 'SETTING_SYSTEM_ID_IN_GAME5';
const SETTING_SYSTEM_RUBY_CONTENT5 = 'SETTING_SYSTEM_RUBY_CONTENT5';
const SETTING_SYSTEM_RUBY_PHONE5 = 'SETTING_SYSTEM_RUBY_PHONE5';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_5 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_5';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_5 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_5';

const SETTING_SYSTEM_RUBY_TITLE6 = 'SETTING_SYSTEM_RUBY_TITLE6';
const SETTING_SYSTEM_RUBY_NOW6 = 'SETTING_SYSTEM_RUBY_NOW6';
const SETTING_SYSTEM_DROPDOWN_NAME6 = 'SETTING_SYSTEM_DROPDOWN_NAME6';
const SETTING_SYSTEM_ID_IN_GAME6 = 'SETTING_SYSTEM_ID_IN_GAME6';
const SETTING_SYSTEM_RUBY_CONTENT6 = 'SETTING_SYSTEM_RUBY_CONTENT6';
const SETTING_SYSTEM_RUBY_PHONE6 = 'SETTING_SYSTEM_RUBY_PHONE6';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_6 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_6';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_6 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_6';


const SETTING_SYSTEM_RUBY_TITLE7 = 'SETTING_SYSTEM_RUBY_TITLE7';
const SETTING_SYSTEM_RUBY_NOW7 = 'SETTING_SYSTEM_RUBY_NOW7';
const SETTING_SYSTEM_DROPDOWN_NAME7 = 'SETTING_SYSTEM_DROPDOWN_NAME7';
const SETTING_SYSTEM_ID_IN_GAME7 = 'SETTING_SYSTEM_ID_IN_GAME7';
const SETTING_SYSTEM_RUBY_CONTENT7 = 'SETTING_SYSTEM_RUBY_CONTENT7';
const SETTING_SYSTEM_RUBY_PHONE7 = 'SETTING_SYSTEM_RUBY_PHONE7';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_7 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_7';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_7 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_7';

const SETTING_SYSTEM_RUBY_TITLE8 = 'SETTING_SYSTEM_RUBY_TITLE8';
const SETTING_SYSTEM_RUBY_NOW8 = 'SETTING_SYSTEM_RUBY_NOW8';
const SETTING_SYSTEM_DROPDOWN_NAME8 = 'SETTING_SYSTEM_DROPDOWN_NAME8';
const SETTING_SYSTEM_ID_IN_GAME8 = 'SETTING_SYSTEM_ID_IN_GAME8';
const SETTING_SYSTEM_RUBY_CONTENT8 = 'SETTING_SYSTEM_RUBY_CONTENT8';
const SETTING_SYSTEM_RUBY_PHONE8 = 'SETTING_SYSTEM_RUBY_PHONE8';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_8 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_8';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_8 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_8';


const SETTING_SYSTEM_RUBY_TITLE9 = 'SETTING_SYSTEM_RUBY_TITLE9';
const SETTING_SYSTEM_RUBY_NOW9 = 'SETTING_SYSTEM_RUBY_NOW9';
const SETTING_SYSTEM_DROPDOWN_NAME9 = 'SETTING_SYSTEM_DROPDOWN_NAME9';
const SETTING_SYSTEM_ID_IN_GAME9 = 'SETTING_SYSTEM_ID_IN_GAME9';
const SETTING_SYSTEM_RUBY_CONTENT9 = 'SETTING_SYSTEM_RUBY_CONTENT9';
const SETTING_SYSTEM_RUBY_PHONE9 = 'SETTING_SYSTEM_RUBY_PHONE9';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_9 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_9';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_9 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_9';

const SETTING_SYSTEM_RUBY_TITLE10 = 'SETTING_SYSTEM_RUBY_TITLE10';
const SETTING_SYSTEM_RUBY_NOW10 = 'SETTING_SYSTEM_RUBY_NOW10';
const SETTING_SYSTEM_DROPDOWN_NAME10 = 'SETTING_SYSTEM_DROPDOWN_NAME10';
const SETTING_SYSTEM_ID_IN_GAME10 = 'SETTING_SYSTEM_ID_IN_GAME10';
const SETTING_SYSTEM_RUBY_CONTENT10 = 'SETTING_SYSTEM_RUBY_CONTENT10';
const SETTING_SYSTEM_RUBY_PHONE10 = 'SETTING_SYSTEM_RUBY_PHONE10';
const SETTING_SYSTEM_RUBY_INFO_PLUS2_10 = 'SETTING_SYSTEM_RUBY_INFO_PLUS2_10';
const SETTING_SYSTEM_RUBY_INFO_PLUS3_10 = 'SETTING_SYSTEM_RUBY_INFO_PLUS3_10';

// cau hinh vong quay
const SETTING_SYSTEM_ROLL_IMAGE = 'SETTING_SYSTEM_ROLL_IMAGE';
const SETTING_SYSTEM_ROLL_FEE = 'SETTING_SYSTEM_ROLL_FEE';
const SETTING_SYSTEM_ROLL_ORDER = 'SETTING_SYSTEM_ROLL_ORDER';
const SETTING_SYSTEM_ROLL_ORDER_USER = 'SETTING_SYSTEM_ROLL_ORDER_USER';
const SETTING_SYSTEM_ROLL_CONTENT1 = 'SETTING_SYSTEM_ROLL_CONTENT1';
const SETTING_SYSTEM_ROLL_CONTENT2 = 'SETTING_SYSTEM_ROLL_CONTENT2';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB';
const SETTING_SYSTEM_ROLL_NAME = 'SETTING_SYSTEM_ROLL_NAME';

const SETTING_SYSTEM_ROLL_IMAGE1 = 'SETTING_SYSTEM_ROLL_IMAGE1';
const SETTING_SYSTEM_ROLL_FEE1 = 'SETTING_SYSTEM_ROLL_FEE1';
const SETTING_SYSTEM_ROLL_ORDER1 = 'SETTING_SYSTEM_ROLL_ORDER1';
const SETTING_SYSTEM_ROLL_ORDER_USER1 = 'SETTING_SYSTEM_ROLL_ORDER_USER1';
const SETTING_SYSTEM_ROLL_CONTENT11 = 'SETTING_SYSTEM_ROLL_CONTENT11';
const SETTING_SYSTEM_ROLL_CONTENT12 = 'SETTING_SYSTEM_ROLL_CONTENT12';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB1 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB1';
const SETTING_SYSTEM_ROLL_NAME1 = 'SETTING_SYSTEM_ROLL_NAME1';

const SETTING_SYSTEM_ROLL_IMAGE2 = 'SETTING_SYSTEM_ROLL_IMAGE2';
const SETTING_SYSTEM_ROLL_FEE2 = 'SETTING_SYSTEM_ROLL_FEE2';
const SETTING_SYSTEM_ROLL_ORDER2 = 'SETTING_SYSTEM_ROLL_ORDER2';
const SETTING_SYSTEM_ROLL_ORDER_USER2 = 'SETTING_SYSTEM_ROLL_ORDER_USER2';
const SETTING_SYSTEM_ROLL_CONTENT21 = 'SETTING_SYSTEM_ROLL_CONTENT21';
const SETTING_SYSTEM_ROLL_CONTENT22 = 'SETTING_SYSTEM_ROLL_CONTENT22';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB2 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB2';
const SETTING_SYSTEM_ROLL_NAME2 = 'SETTING_SYSTEM_ROLL_NAME2';

const SETTING_SYSTEM_ROLL_IMAGE3 = 'SETTING_SYSTEM_ROLL_IMAGE3';
const SETTING_SYSTEM_ROLL_FEE3 = 'SETTING_SYSTEM_ROLL_FEE3';
const SETTING_SYSTEM_ROLL_ORDER3 = 'SETTING_SYSTEM_ROLL_ORDER3';
const SETTING_SYSTEM_ROLL_ORDER_USER3 = 'SETTING_SYSTEM_ROLL_ORDER_USER3';
const SETTING_SYSTEM_ROLL_CONTENT31 = 'SETTING_SYSTEM_ROLL_CONTENT31';
const SETTING_SYSTEM_ROLL_CONTENT32 = 'SETTING_SYSTEM_ROLL_CONTENT32';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB3 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB3';
const SETTING_SYSTEM_ROLL_NAME3 = 'SETTING_SYSTEM_ROLL_NAME3';

const SETTING_SYSTEM_ROLL_IMAGE4 = 'SETTING_SYSTEM_ROLL_IMAGE4';
const SETTING_SYSTEM_ROLL_FEE4 = 'SETTING_SYSTEM_ROLL_FEE4';
const SETTING_SYSTEM_ROLL_ORDER4 = 'SETTING_SYSTEM_ROLL_ORDER4';
const SETTING_SYSTEM_ROLL_ORDER_USER4 = 'SETTING_SYSTEM_ROLL_ORDER_USER4';
const SETTING_SYSTEM_ROLL_CONTENT41 = 'SETTING_SYSTEM_ROLL_CONTENT41';
const SETTING_SYSTEM_ROLL_CONTENT42 = 'SETTING_SYSTEM_ROLL_CONTENT42';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB4 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB4';
const SETTING_SYSTEM_ROLL_NAME4 = 'SETTING_SYSTEM_ROLL_NAME4';

const SETTING_SYSTEM_ROLL_IMAGE5 = 'SETTING_SYSTEM_ROLL_IMAGE5';
const SETTING_SYSTEM_ROLL_FEE5 = 'SETTING_SYSTEM_ROLL_FEE5';
const SETTING_SYSTEM_ROLL_ORDER5 = 'SETTING_SYSTEM_ROLL_ORDER5';
const SETTING_SYSTEM_ROLL_ORDER_USER5 = 'SETTING_SYSTEM_ROLL_ORDER_USER5';
const SETTING_SYSTEM_ROLL_CONTENT51 = 'SETTING_SYSTEM_ROLL_CONTENT51';
const SETTING_SYSTEM_ROLL_CONTENT52 = 'SETTING_SYSTEM_ROLL_CONTENT52';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB5 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB5';
const SETTING_SYSTEM_ROLL_NAME5 = 'SETTING_SYSTEM_ROLL_NAME5';

const SETTING_SYSTEM_ROLL_IMAGE6 = 'SETTING_SYSTEM_ROLL_IMAGE6';
const SETTING_SYSTEM_ROLL_FEE6 = 'SETTING_SYSTEM_ROLL_FEE6';
const SETTING_SYSTEM_ROLL_ORDER6 = 'SETTING_SYSTEM_ROLL_ORDER6';
const SETTING_SYSTEM_ROLL_ORDER_USER6 = 'SETTING_SYSTEM_ROLL_ORDER_USER6';
const SETTING_SYSTEM_ROLL_CONTENT61 = 'SETTING_SYSTEM_ROLL_CONTENT61';
const SETTING_SYSTEM_ROLL_CONTENT62 = 'SETTING_SYSTEM_ROLL_CONTENT62';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB6 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB6';
const SETTING_SYSTEM_ROLL_NAME6 = 'SETTING_SYSTEM_ROLL_NAME6';

const SETTING_SYSTEM_ROLL_IMAGE7 = 'SETTING_SYSTEM_ROLL_IMAGE7';
const SETTING_SYSTEM_ROLL_FEE7 = 'SETTING_SYSTEM_ROLL_FEE7';
const SETTING_SYSTEM_ROLL_ORDER7 = 'SETTING_SYSTEM_ROLL_ORDER7';
const SETTING_SYSTEM_ROLL_ORDER_USER7 = 'SETTING_SYSTEM_ROLL_ORDER_USER7';
const SETTING_SYSTEM_ROLL_CONTENT71 = 'SETTING_SYSTEM_ROLL_CONTENT71';
const SETTING_SYSTEM_ROLL_CONTENT72 = 'SETTING_SYSTEM_ROLL_CONTENT72';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB7 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB7';
const SETTING_SYSTEM_ROLL_NAME7 = 'SETTING_SYSTEM_ROLL_NAME7';

const SETTING_SYSTEM_ROLL_IMAGE8 = 'SETTING_SYSTEM_ROLL_IMAGE8';
const SETTING_SYSTEM_ROLL_FEE8 = 'SETTING_SYSTEM_ROLL_FEE8';
const SETTING_SYSTEM_ROLL_ORDER8 = 'SETTING_SYSTEM_ROLL_ORDER8';
const SETTING_SYSTEM_ROLL_ORDER_USER8 = 'SETTING_SYSTEM_ROLL_ORDER_USER8';
const SETTING_SYSTEM_ROLL_CONTENT81 = 'SETTING_SYSTEM_ROLL_CONTENT81';
const SETTING_SYSTEM_ROLL_CONTENT82 = 'SETTING_SYSTEM_ROLL_CONTENT82';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB8 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB8';
const SETTING_SYSTEM_ROLL_NAME8 = 'SETTING_SYSTEM_ROLL_NAME8';

const SETTING_SYSTEM_ROLL_IMAGE9 = 'SETTING_SYSTEM_ROLL_IMAGE9';
const SETTING_SYSTEM_ROLL_FEE9 = 'SETTING_SYSTEM_ROLL_FEE9';
const SETTING_SYSTEM_ROLL_ORDER9 = 'SETTING_SYSTEM_ROLL_ORDER9';
const SETTING_SYSTEM_ROLL_ORDER_USER9 = 'SETTING_SYSTEM_ROLL_ORDER_USER9';
const SETTING_SYSTEM_ROLL_CONTENT91 = 'SETTING_SYSTEM_ROLL_CONTENT91';
const SETTING_SYSTEM_ROLL_CONTENT92 = 'SETTING_SYSTEM_ROLL_CONTENT92';
const SETTING_SYSTEM_ROLL_IMAGE_THUMB9 = 'SETTING_SYSTEM_ROLL_IMAGE_THUMB9';
const SETTING_SYSTEM_ROLL_NAME9 = 'SETTING_SYSTEM_ROLL_NAME9';

const SETTING_SYSTEM_COIN_CONTENT = 'SETTING_SYSTEM_COIN_CONTENT';
const SETTING_SYSTEM_GEM_CONTENT = 'SETTING_SYSTEM_GEM_CONTENT';
const SETTING_SYSTEM_XU_CONTENT = 'SETTING_SYSTEM_XU_CONTENT';


//intro-text
const SETTING_SYSTEM_INTRO_TEXT = 'SETTING_SYSTEM_INTRO_TEXT';
const SETTING_SYSTEM_USER_COVER = 'SETTING_SYSTEM_USER_COVER';
const SETTING_SYSTEM_USER_AVATAR = 'SETTING_SYSTEM_USER_AVATAR';

// cau hinh mesage, % vi tri atm, card
const SETTING_SYSTEM_MESSAGER = 'SETTING_SYSTEM_MESSAGER';
const SETTING_SYSTEM_CARD_PERCENT = 'SETTING_SYSTEM_CARD_PERCENT';
const SETTING_SYSTEM_ATM_PERCENT = 'SETTING_SYSTEM_ATM_PERCENT';
const SETTING_SYSTEM_CARD_POSITION = 'SETTING_SYSTEM_CARD_POSITION';
const SETTING_SYSTEM_ATM_POSITION = 'SETTING_SYSTEM_ATM_POSITION';

//

//SETTING TELECOM SLOW
const SETTING_NOTICE_CHARGE_SLOW = 'SETTING_NOTICE_CHARGE_SLOW';
const SETTING_NOTICE_CHARGE_AUTO = 'SETTING_NOTICE_CHARGE_AUTO';
const SETTING_NOTICE_STORE_TELECOM = 'SETTING_NOTICE_STORE_TELECOM';

const SETTING_NOTICE_BANK = 'SETTING_NOTICE_BANK';

const SETTING_ADVERTISEMENT_RECEIVE_MAIL_COMMENT='SETTING_ADVERTISEMENT_RECEIVE_MAIL_COMMENT';
const SETTING_ADVERTISEMENT_ACTIVE_COMMENT='SETTING_ADVERTISEMENT_ACTIVE_COMMENT';
const SETTING_ADVERTISEMENT_IMAGE_WIDTH='SETTING_ADVERTISEMENT_IMAGE_WIDTH';
const SETTING_ADVERTISEMENT_IMAGE_HEIGHT='SETTING_ADVERTISEMENT_IMAGE_HEIGHT';



const APP_CLIENT="nick.vn";

const LIMIT_FAIL_CHARGE=6;
const BLOCK_CHARGE_TIME=10;


const MONEY_LIMIT_DEFAULT=10000000;
const KEYDECRYPT="136G2d35ccha";

const ID_NROCOIN=1801;
const ID_NROGEM=1802;
const ID_LANGLACOIN=1803;
const ID_NINJAXU=1795;
const ID_ROBLOXBUYSERVER=1811;
const ID_ROBLOXBUYGAMEPASS=1812;
const ID_BANTIENDIENTHOAI=164133;
const ID_NAPCUOCLE=157206;
const ID_NAPSMS9029=93240;
const ID_ROBLOXBUYPET=1813;


